// Official gallery images, indexed by name to include starter and synthetic cards.
export const CARD_ART: Readonly<Record<string, string>> = {
  "Arkus, Imperial Dragon": "hr_001.jpg",
  "Close Ranks": "hr_002.jpg",
  Command: "hr_003.jpg",
  "Darian, War Mage": "hr_004.jpg",
  Domination: "hr_005.jpg",
  "Cristov, the Just": "hr_006.jpg",
  "Kraka, High Priest": "hr_007.jpg",
  "Man-at-Arms": "hr_008.jpg",
  "Master Weyan": "hr_009.jpg",
  "Rally the Troops": "hr_010.jpg",
  Recruit: "hr_011.jpg",
  "Tithe Priest": "hr_012.jpg",
  Taxation: "hr_013.jpg",
  "Word of Power": "hr_014.jpg",
  "Borg, Ogre Mercenary": "hr_015.jpg",
  Bribe: "hr_016.jpg",
  "Death Threat": "hr_017.jpg",
  Deception: "hr_018.jpg",
  "Fire Bomb": "hr_019.jpg",
  "Hit Job": "hr_020.jpg",
  Intimidation: "hr_021.jpg",
  "Myros, Guild Mage": "hr_022.jpg",
  "Parov, the Enforcer": "hr_023.jpg",
  Profit: "hr_024.jpg",
  "Rake, Master Assassin": "hr_025.jpg",
  "Rasmus, the Smuggler": "hr_026.jpg",
  "Smash and Grab": "hr_027.jpg",
  "Street Thug": "hr_028.jpg",
  "Cult Priest": "hr_029.jpg",
  "Dark Energy": "hr_030.jpg",
  "Dark Reward": "hr_031.jpg",
  "Death Cultist": "hr_032.jpg",
  "Death Touch": "hr_033.jpg",
  "Rayla, Endweaver": "hr_034.jpg",
  Influence: "hr_035.jpg",
  "Krythos, Master Vampire": "hr_036.jpg",
  "Life Drain": "hr_037.jpg",
  "Lys, the Unseen": "hr_038.jpg",
  "The Rot": "hr_039.jpg",
  "Tyrannor, the Devourer": "hr_040.jpg",
  "Varrick, the Necromancer": "hr_041.jpg",
  "Broelyn, Loreweaver": "hr_042.jpg",
  "Cron, the Berserker": "hr_043.jpg",
  "Dire Wolf": "hr_044.jpg",
  "Elven Curse": "hr_045.jpg",
  "Elven Gift": "hr_046.jpg",
  "Grak, Storm Giant": "hr_047.jpg",
  "Nature's Bounty": "hr_048.jpg",
  "Orc Grunt": "hr_049.jpg",
  Rampage: "hr_050.jpg",
  "Torgen Rocksplitter": "hr_051.jpg",
  Spark: "hr_052.jpg",
  "Wolf Form": "hr_053.jpg",
  "Wolf Shaman": "hr_054.jpg",
  "Fire Gem": "hr_055.jpg",
  Gold: "gold.jpg",
  Shortsword: "shortsword.jpg",
  Dagger: "dagger.jpg",
  Ruby: "ruby.jpg",
};
